

# This is the Supabase configuration file for Edge Functions

project_id = "amityhneeclqenbiyixl"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

