
project_id = "amityhneeclqenbiyixl"
[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = true

[storage]
enabled = true

# Configure the Stripe webhook function to accept unauthenticated requests
[functions.stripe-webhook]
verify_jwt = false
